// PROTOTYPE — pulls this repo's own wayfinder map into map-fixture.ts.
// Usage (from packages/vscode): node webview/src/prototype/refresh-fixture.mjs
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const query = `
query {
  repository(owner: "dbarjs", name: "hero-synergy") {
    issue(number: 1) {
      number title url body
      subIssues(first: 50) {
        nodes {
          number title url state body
          labels(first: 10) { nodes { name } }
          assignees(first: 5) { nodes { login } }
          blockedBy(first: 20) { nodes { number } }
        }
      }
    }
  }
}`

const raw = execFileSync('gh', ['api', 'graphql', '-f', `query=${query}`], { encoding: 'utf8' })
const map = JSON.parse(raw).data.repository.issue

const section = (name) => {
  const match = map.body.match(new RegExp(`## ${name}\\n([\\s\\S]*?)(?=\\n## |$)`))
  return match ? match[1].replace(/<!--[\s\S]*?-->/g, '').trim() : ''
}
const bullets = (text) =>
  text
    .split('\n')
    .filter((line) => line.startsWith('- '))
    .map((line) => line.slice(2))
const issueNumbers = (text) => [...text.matchAll(/\/issues\/(\d+)\)/g)].map((m) => Number(m[1]))
const unlink = (text) => text.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')

const gists = new Map(
  bullets(section('Decisions so far')).map((line) => [
    issueNumbers(line)[0],
    line.replace(/^\[[^\]]+\]\([^)]+\)\s+—\s+/, ''),
  ]),
)

const fixture = {
  number: map.number,
  title: map.title,
  url: map.url,
  destination: unlink(section('Destination')),
  tickets: map.subIssues.nodes.map((node) => ({
    number: node.number,
    title: node.title,
    url: node.url,
    state: node.state,
    type: node.labels.nodes
      .map((l) => l.name)
      .find((n) => n.startsWith('wayfinder:'))
      ?.slice(10),
    assignee: node.assignees.nodes[0]?.login ?? null,
    blockedBy: node.blockedBy.nodes.map((b) => b.number),
    question: unlink((node.body.match(/## Question\n+([^\n]+)/) ?? [])[1] ?? ''),
    gist: gists.get(node.number) ?? null,
  })),
  fog: bullets(section('Not yet specified')).map((line) => {
    const [, title, rest] = line.match(/^\*\*(.+?)\.\*\*\s*(.*)$/)
    const [text] = rest.split(/\s*Waits on /)
    return { title, text: unlink(text), waitsOn: issueNumbers(line) }
  }),
  outOfScope: bullets(section('Out of scope')).map((line) => unlink(line).replace(/\*\*/g, '')),
}

writeFileSync(
  new URL('./map-fixture.ts', import.meta.url),
  `// PROTOTYPE — generated by refresh-fixture.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit.\nimport type { MapData } from './data.ts'\n\nexport const fixture: MapData = ${JSON.stringify(fixture, null, 2)}\n`,
)
console.log(`${fixture.tickets.length} tickets, ${fixture.fog.length} fog patches`)
