#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ticket "Create and install the dbarjs-agent App" (#164) on the map "Only
# Eduardo merges to main" (#159). GitHub builds the private App from a
# manifest, so no permission can be mis-clicked, and the private key comes
# straight from GitHub's API into this container. Every API call is either
# unauthenticated or made as the App: the gh login is never used.
#
# Run it from a VS Code terminal in the devcontainer, which forwards the
# callback port to your browser. Re-running skips whatever is already done.
#
# The WIZARD_* variables exist for the mock run in dbarjs-agent-app.test.sh.

TOTAL_STAGES=3

OWNER=dbarjs
REPO=hero-synergy
APP_NAME=dbarjs-agent
GITHUB_URL="${WIZARD_GITHUB_URL:-https://github.com}"
API_URL="${WIZARD_API_URL:-https://api.github.com}"
PORT="${WIZARD_PORT:-31164}"
AGENT_DIR="${WIZARD_DIR:-$HOME/.config/dbarjs-agent}"
KEY="$AGENT_DIR/private-key.pem"
ENV_FILE="$AGENT_DIR/app.env"
WANT_PERMISSIONS='{"contents":"write","issues":"write","metadata":"read","pull_requests":"write","workflows":"write"}'

for tool in curl jq node openssl; do
  command -v "$tool" >/dev/null 2>&1 || { printf '%s is missing: install it and re-run.\n' "$tool" >&2; exit 1; }
done
if [[ ! -t 0 && -z "${WIZARD_NO_TTY:-}" ]]; then
  printf 'Run this from a terminal: it waits for you at every step.\n' >&2
  exit 1
fi

WORK=$(mktemp -d)
SERVER_PID=""
cleanup() {
  if [[ -n "$SERVER_PID" ]]; then kill "$SERVER_PID" 2>/dev/null || true; fi
  rm -rf "$WORK"
}
trap cleanup EXIT

# VS Code's remote terminal opens URLs on the host through $BROWSER, and
# open_url looks for xdg-open: bridge the two.
if ! command -v xdg-open >/dev/null 2>&1 && [[ -n "${BROWSER:-}" ]]; then
  mkdir "$WORK/bin"
  # shellcheck disable=SC2016 # $BROWSER expands when the shim runs
  printf '#!/bin/sh\nexec "$BROWSER" "$@"\n' >"$WORK/bin/xdg-open"
  chmod +x "$WORK/bin/xdg-open"
  PATH="$WORK/bin:$PATH"
fi

mkdir -p "$AGENT_DIR"
chmod 700 "$AGENT_DIR"

fail() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET"
  if [[ -n "${2:-}" ]]; then note "$2"; fi
  printf '\n'
  exit 1
}
ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# api METHOD PATH [TOKEN] — call the REST API; sets STATUS and BODY.
api() {
  local auth=() out
  if [[ -n "${3:-}" ]]; then auth=(-H "Authorization: Bearer $3"); fi
  out=$(curl -sS -X "$1" "${auth[@]}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -w '\n%{http_code}' "$API_URL$2") || { STATUS=000; BODY=""; return 0; }
  STATUS="${out##*$'\n'}"
  BODY="${out%$'\n'*}"
}

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# jwt — a 10-minute JWT signed with the App's key, for the /app endpoints.
jwt() {
  local now head claims sig
  now=$(date +%s)
  head=$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)
  claims=$(printf '{"iat":%s,"exp":%s,"iss":"%s"}' "$((now - 60))" "$((now + 540))" "$CLIENT_ID" | b64url)
  sig=$(printf '%s.%s' "$head" "$claims" | openssl dgst -sha256 -sign "$KEY" -binary | b64url)
  printf '%s.%s.%s' "$head" "$claims" "$sig"
}

# Serves the page that posts the manifest to GitHub, then catches GitHub's
# redirect back and writes the one-time code to a file.
# shellcheck disable=SC2016 # JavaScript template literals, not shell
SERVER_JS='
const http = require("node:http");
const fs = require("node:fs");
const [port, state, manifestFile, codeFile, githubUrl] = process.argv.slice(1);
const manifest = fs.readFileSync(manifestFile, "utf8");
const esc = (s) => s.replace(/[&<>"\x27]/g, (c) => `&#${c.charCodeAt(0)};`);
const page = (body) =>
  `<!doctype html><meta charset="utf-8"><title>dbarjs-agent</title>` +
  `<body style="font:16px system-ui;margin:3rem;max-width:40rem">${body}</body>`;
const server = http.createServer((req, res) => {
  const url = new URL(req.url, "http://localhost");
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  if (url.pathname === "/") {
    res.end(page(
      `<p>Sending the dbarjs-agent manifest to GitHub…</p>` +
      `<form id="f" method="post" action="${esc(`${githubUrl}/settings/apps/new?state=${state}`)}">` +
      `<input type="hidden" name="manifest" value="${esc(manifest)}">` +
      `<button>Continue to GitHub</button></form>` +
      `<script>document.getElementById("f").submit()</script>`,
    ));
  } else if (url.pathname === "/callback" && url.searchParams.get("state") === state && url.searchParams.get("code")) {
    fs.writeFileSync(codeFile, url.searchParams.get("code"), { mode: 0o600 });
    res.end(page("<p>GitHub created the App. Go back to the terminal.</p>"));
  } else {
    res.statusCode = 400;
    res.end(page("<p>That request is not from this run. Go back to the terminal.</p>"));
  }
});
server.listen(Number(port), "127.0.0.1");
'

banner "Create and install the dbarjs-agent App (#164)"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Create the App"
APP_ID=$(_existing DBARJS_AGENT_APP_ID || true)
SLUG=$(_existing DBARJS_AGENT_SLUG || true)
CLIENT_ID=$(_existing DBARJS_AGENT_CLIENT_ID || true)
if [[ -n "$APP_ID" && -n "$SLUG" && -n "$CLIENT_ID" && -s "$KEY" ]]; then
  ok "Already created: $SLUG (App ID $APP_ID), key at $KEY."
else
  say "GitHub creates the private App $APP_NAME under $OWNER from this manifest:"
  note "  Contents, Pull requests, Issues, Workflows: read and write"
  note "  Metadata: read · everything else: no access"
  note "  No webhook · only on this account"
  printf '\n'

  state=$(openssl rand -hex 16)
  jq -n \
    --arg name "$APP_NAME" \
    --arg home "$GITHUB_URL/$OWNER" \
    --arg redirect "http://localhost:$PORT/callback" \
    --arg about "Agent sessions' GitHub identity: pushes branches and opens PRs, never merges. See $OWNER/$REPO#159." \
    '{
      name: $name,
      url: $home,
      description: $about,
      public: false,
      hook_attributes: { url: $home, active: false },
      redirect_url: $redirect,
      default_events: [],
      default_permissions: {
        contents: "write",
        pull_requests: "write",
        issues: "write",
        workflows: "write",
        metadata: "read"
      }
    }' >"$WORK/manifest.json"
  node -e "$SERVER_JS" "$PORT" "$state" "$WORK/manifest.json" "$WORK/code" "$GITHUB_URL" &
  SERVER_PID=$!
  for _ in $(seq 50); do
    curl -fsS -o /dev/null "http://127.0.0.1:$PORT/" 2>/dev/null && break
    kill -0 "$SERVER_PID" 2>/dev/null || fail "Port $PORT is taken." "Free it, or re-run with WIZARD_PORT set to another port."
    sleep 0.1
  done

  open_url "http://localhost:$PORT/"
  step "Your browser posts the manifest to GitHub. Check the name reads $APP_NAME,"
  step "then click \"Create GitHub App for $OWNER\". GitHub may ask for your password."
  note "  If GitHub says the name is taken, pick a close variant: the wizard follows it."
  step "GitHub sends you back to a page that says to return to the terminal."
  note "  If that page won't load, copy the address your browser ended on instead."
  code=""
  while [[ -z "$code" ]]; do
    ask CALLBACK "Press Enter when done, or paste that address:"
    if [[ "$CALLBACK" == *code=* ]]; then
      if [[ "$CALLBACK" != *"state=$state"* ]]; then
        warn "That address belongs to another run. Use the one from this run."
        continue
      fi
      code=$(sed -E 's/.*[?&]code=([^&#]+).*/\1/' <<<"$CALLBACK")
    elif [[ -s "$WORK/code" ]]; then
      code=$(<"$WORK/code")
    else
      warn "GitHub hasn't sent the code back yet."
    fi
  done
  kill "$SERVER_PID" 2>/dev/null || true
  SERVER_PID=""

  api POST "/app-manifests/$code/conversions"
  [[ "$STATUS" == 201 ]] || fail "GitHub didn't hand over the new App (HTTP $STATUS)." \
    "If $GITHUB_URL/settings/apps lists it, delete it there (Advanced → Delete GitHub App) and re-run."
  (umask 077 && jq -j .pem <<<"$BODY" >"$KEY")
  chmod 600 "$KEY"
  APP_ID=$(jq -r .id <<<"$BODY")
  SLUG=$(jq -r .slug <<<"$BODY")
  CLIENT_ID=$(jq -r .client_id <<<"$BODY")
  BODY="" # it also held the client and webhook secrets, which nothing needs
  ok "Created $SLUG (App ID $APP_ID)."
  ok "Wrote the private key to $KEY (mode 600)."
  write_env DBARJS_AGENT_APP_ID "$APP_ID"
  write_env DBARJS_AGENT_SLUG "$SLUG"
  write_env DBARJS_AGENT_CLIENT_ID "$CLIENT_ID"
  write_env DBARJS_AGENT_KEY "$KEY"
fi
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Install it on $REPO only"
asked=""
while :; do
  api GET "/repos/$OWNER/$REPO/installation" "$(jwt)"
  [[ "$STATUS" == 200 ]] && break
  [[ "$STATUS" == 404 ]] || fail "GitHub refused the App's own credentials (HTTP $STATUS)." \
    "Check that $KEY is a current key on $GITHUB_URL/settings/apps/$SLUG."
  if [[ -n "$asked" ]]; then warn "It isn't installed on $OWNER/$REPO yet."; fi
  open_url "$GITHUB_URL/apps/$SLUG/installations/new"
  step "Install it on your account ($OWNER)."
  step "Choose \"Only select repositories\" and pick $OWNER/$REPO, nothing else."
  step "Click Install."
  pause "Press Enter once it's installed."
  asked=1
done
INSTALL="$BODY"
INSTALLATION_ID=$(jq -r .id <<<"$INSTALL")
ok "Installed: installation $INSTALLATION_ID."
write_env DBARJS_AGENT_INSTALLATION_ID "$INSTALLATION_ID"
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Check what the App can reach"
SETTINGS="$GITHUB_URL/settings/installations/$INSTALLATION_ID"

[[ $(jq -r .account.login <<<"$INSTALL") == "$OWNER" ]] || fail "It's installed on the wrong account." \
  "Uninstall it at $SETTINGS and re-run."
[[ $(jq -r .repository_selection <<<"$INSTALL") == selected ]] || fail "It's installed on all repositories." \
  "At $SETTINGS switch to \"Only select repositories\", keep only $REPO, save, and re-run."
got=$(jq -cS .permissions <<<"$INSTALL")
[[ "$got" == "$WANT_PERMISSIONS" ]] || fail "It holds $got." \
  "It should hold exactly $WANT_PERMISSIONS. Fix it at $GITHUB_URL/settings/apps/$SLUG/permissions, accept the change at $SETTINGS, and re-run."
ok "Permissions: Contents, Pull requests, Issues and Workflows write, Metadata read, nothing else."

api GET /app "$(jwt)"
[[ "$STATUS" == 200 ]] || fail "GitHub refused the App's JWT (HTTP $STATUS)."
[[ $(jq -r .owner.login <<<"$BODY") == "$OWNER" ]] || fail "The App isn't owned by $OWNER."
[[ $(jq -c .events <<<"$BODY") == "[]" ]] || fail "The App subscribes to events: $(jq -c .events <<<"$BODY")." \
  "Clear them at $GITHUB_URL/settings/apps/$SLUG/permissions and re-run."
api GET "/apps/$SLUG"
[[ "$STATUS" == 404 ]] || fail "The App is public." \
  "Make it private at $GITHUB_URL/settings/apps/$SLUG/advanced and re-run."
ok "Owned by $OWNER, private, no webhook events."

api POST "/app/installations/$INSTALLATION_ID/access_tokens" "$(jwt)"
[[ "$STATUS" == 201 ]] || fail "The App couldn't mint an installation token (HTTP $STATUS)."
TOKEN=$(jq -r .token <<<"$BODY")
api GET "/installation/repositories?per_page=100" "$TOKEN"
repos=$(jq -r '[.repositories[].full_name] | join(", ")' <<<"$BODY")
api DELETE /installation/token "$TOKEN"
TOKEN=""
if [[ "$STATUS" != 204 ]]; then warn "Couldn't revoke the check's token (HTTP $STATUS); it expires within the hour."; fi
[[ "$repos" == "$OWNER/$REPO" ]] || fail "It reaches $repos." \
  "At $SETTINGS keep only $REPO, save, and re-run."
ok "A token it mints reaches $OWNER/$REPO and nothing else."

BOT_LOGIN="${SLUG}[bot]"
api GET "/users/$SLUG%5Bbot%5D"
[[ "$STATUS" == 200 ]] || fail "GitHub doesn't know the bot user $BOT_LOGIN yet (HTTP $STATUS)." "Wait a minute and re-run."
BOT_ID=$(jq -r .id <<<"$BODY")
ok "Bot user: $BOT_LOGIN (user ID $BOT_ID)."
write_env DBARJS_AGENT_BOT_LOGIN "$BOT_LOGIN"
write_env DBARJS_AGENT_BOT_ID "$BOT_ID"
pause

finish
say "${BOLD}For \"Create and install the dbarjs-agent App\" (#164):${RESET}"
note "  App:           $SLUG (App ID $APP_ID, client ID $CLIENT_ID)"
note "  Installation:  $INSTALLATION_ID, on $OWNER/$REPO only"
note "  Bot user:      $BOT_LOGIN (user ID $BOT_ID)"
note "  Private key:   $KEY"
note "  All of it:     $ENV_FILE"
printf '\n'
warn "The key lives only in this container, so a rebuild deletes it. \"Run agent"
note "  sessions as the App, not Eduardo\" (#165) gives it a permanent home. A lost"
note "  key is replaced from $GITHUB_URL/settings/apps/$SLUG."
printf '\n'
say "Next: in Claude Code, run /wayfinder #159 #164 to record this and close the ticket."
printf '\n'
